name: Reset Generated Content

on:
  workflow_dispatch:
    inputs:
      confirm:
        description: 'Type RESET to confirm deleting ALL generated articles and images'
        required: true
        default: 'RESET'

permissions:
  contents: write

jobs:
  reset:
    if: github.event.inputs.confirm == 'RESET'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Run reset script
        run: |
          python scripts/reset_site.py

      - name: Commit and push changes (if any)
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add -A
            git commit -m "chore(reset): delete generated content and reset data [skip ci]"
            git push
          else
            echo "No changes to commit."
          fi
